### ISSUE TITLE
Possible typo in Jumps

### ISSUE THREAD

**Issue by r00ster91** [ISSOtm/gb-asm-tutorial-v2#3]
From https://eldred.fr/gb-asm-tutorial-v2/part1/jumps.html#conditional-jumps:

> `ld bc, Tiles.end - Tiles` sets `bc` to the length of the tile data: `Tiles.end` is the address of the first byte *after* the tile data, so subtracting `Tiles` to that yields the length.

`Tiles.end` should probably be `TilesEnd`. I couldn't find this source in this repository so I wasn't able to submit a PR.

**Comment by ISSOtm** [comment]
Fixed locally, closing. Thanks!
