### ISSUE TITLE
Asciinema is broken on the hello world page

### ISSUE THREAD

**Issue by NieDzejkob** [ISSOtm/gb-asm-tutorial-v2#4]
On [this page](https://eldred.fr/gb-asm-tutorial-v2/part1/hello_world.html), there's supposed to be an embedded Asciinema recording, but as the server reports 502 Bad Gateway, there's nothing there.

**Comment by ISSOtm** [comment]
That's the hosting site having some trouble. I've reported it, but since I can't do anything else about it, I'll be closing this. Thanks!
